name: Rebuild Server

on:
  push:
    branches:
      - main

jobs:
  rebuild:
    runs-on: ThirtyOneIron

    steps:
      - name: Start System Rebuild
        run: systemctl start --no-block rebuild-system.service
