name: Rebuild Server

on:
  push:
    branches:
      - main

jobs:
  rebuild:
    runs-on: ThirtyOneIron

    steps:
      - name: Start System Rebuild
        run: systemctl start --no-block rebuild-system.service

      - name: Wait to Confirm Build
        run: |
          echo "Waiting for build"
          sleep 1

          while [ "$(systemctl show -p ActiveState --value rebuild-system.service)" != "inactive" ] && \
                [ "$(systemctl show -p ActiveState --value rebuild-system.service)" != "failed" ]; do
            sleep 1
          done

          if systemctl is-failed --quiet rebuild-system.service; then
            journalctl -u rebuild-system.service -n 50 --no-pager
            exit 1
          fi
